---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q11
  labels:
    question.kontest.amsy.dev: "11"
data:
  question: |-
    cndt-pvcという名前のPersistentVolumeClaimで要求したPersistentVolumeを、cndt-podという名前でmountPath:/usr/share/nginx/htmlにマウントするように以下マニフェストファイルを変更してください。

    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  hint: |-
    https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: cndt-pod
      volumes:
        - name: cndt-pod
          persistentVolumeClaim:
            claimName: cndt-pvc
  comment: |-
    【解説 by カサレアル】
    まず spec.volumes[].persistentVolumeClaim.claimName に、PersistentVolumeClaim名を指定します。併せて spec.volumes[].name に任意のボリューム名を指定します（今回はcndt-pod）。
    そして spec.containers[].volumeMounts[] の name にボリューム名、 mountPath にマウント先のパスを指定します。
    同一Pod内であれば、どのコンテナにも同じ名前で参照するだけでマウント可能です。これにより、Pod内のコンテナ間でデータを共有することができます。
  author: |-
    Yutaka Ichikawa (@cyberblack28)
