---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q12
  labels:
    question.kontest.amsy.dev: "12"
data:
  question: |-
    Kubernetesでは、ラベル機能を利用して特定のノードにPodを配置する方法があります。
    arch=amd64のラベルを持つノードにcndt-redisという名前のPodが配置されるように以下マニフェストファイルを変更してください。

    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-redis
      name: cndt-redis
    spec:
      containers:
      - image: redis
        name: cndt-redis
  hint: |-
    https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-redis
      name: cndt-redis
    spec:
      containers:
      - image: redis
        name: cndt-redis
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-redis
      name: cndt-redis
    spec:
      containers:
      - image: redis
        name: cndt-redis
      nodeSelector:
        arch: amd64
  comment: |-
    this is comment here after correct answer
  author: |-
    Yutaka Ichikawa (@cyberblack28)
