---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q13
  labels:
    question.kontest.amsy.dev: "13"
data:
  question: |-
    Kubernetesでは、Podの一時ディスク領域として利用できる機能があります。Podのdeleteと同時にその領域も削除されます。
    tmp-volという名前で/tmpを一時的なディスク領域として利用できるように、以下マニフェストファイルを変更してください。
    
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
  hint: |-
    https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
        volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: tmp-vol
        emptyDir: {}
  comment: |-
    this is comment here after correct answer
  author: |-
    Yutaka Ichikawa (@cyberblack28)
