---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q13
  labels:
    question.kontest.amsy.dev: "13"
data:
  question: |-
    Empty Dirを使うと、Podに対して一時的なディスク領域をマウントすることができます。この領域は、Podのdeleteと同時に削除されます。
    tmp-volという名前で/tmpを一時的なディスク領域（Empty Dir）として利用できるように、以下マニフェストファイルを変更してください。
    
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
  hint: |-
    https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx
        name: cndt-nginx
        volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: tmp-vol
        emptyDir: {}
  comment: |-
    【解説 by カサレアル】
    emptyDirは同一Pod内でのみ共有されるボリュームです。ライフサイクルはPodと同じです（Podが作成されるとemptyDirが作成され、Podが削除されるとemptyDirも削除される）。
    spec.volumes.emptyDirには medium （ストレージのメディア）と sizeLimit （データ容量の上限値）という属性があります。 {} を指定すると、これらの属性はデフォルト値になります。（それぞれ ""（ノードのデフォルトメディア）、nil（無制限））
  author: |-
    Yutaka Ichikawa (@cyberblack28)
