---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q15
  labels:
    question.kontest.amsy.dev: "15"
data:
  question: |-
    個々のコンテナに対するセキュリティ設定として、SecurityContextがあります。
    特権コンテナを利用できるように以下マニフェストファイルを変更してください。
    
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.19
        name: cndt-nginx
  hint: |-
    https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.19
        name: cndt-nginx
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.19
        name: cndt-nginx
        securityContext:
          privileged: true
  comment: |-
    【解説 by カサレアル】
    PodSecurityContextがPod内の全コンテナに対する共通のセキュリティ設定であることに対して、SecurityContextはPod内の各コンテナに対するセキュリティ設定です。この2つで設定が重複した場合は、SecurityContextの設定が優先されます。
    SecurityContextは spec.containers[].securityContext で設定します。 privilaged の値を true に設定すると、そのコンテナは特権モードで実行されます。
  author: |-
    Yutaka Ichikawa (@cyberblack28)
