---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q15
  labels:
    question.kontest.amsy.dev: "15"
data:
  question: |-
    Kubernetesでは、個々のコンテナに対するセキュリティ設定として、SecurityContextがあります。
    特権コンテナを利用できるように以下マニフェストファイルを変更してください。
    
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.18
        name: cndt-nginx
  hint: |-
    https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.18
        name: cndt-nginx
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        run: cndt-nginx
      name: cndt-nginx
    spec:
      containers:
      - image: nginx:1.18
        name: cndt-nginx
        securityContext:
          privileged: true
  comment: |-
    this is comment here after correct answer
  author: |-
    Yutaka Ichikawa (@cyberblack28)
