---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q4
  labels:
    question.kontest.amsy.dev: "4"
data:
  question: |-
    Serviceは複数個のPodに対してロードバランサ相当の機能を提供するもので、ラベルを使って転送先のPodを指定します。
    次のDeploymentに対応するServiceを作成してください。
    なお、Serviceは8181番ポートで受けて、Podの80番ポートに転送するように設定してください。
    
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx-app
      template:
        metadata:
          labels:
            app: nginx-app
        spec:
          containers:
          - name: nginx-container
            image: amsy810/echo-nginx:v2.0

  hint: |-
    https://kubernetes.io/ja/docs/concepts/services-networking/service/
  base_content.yaml: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      type: ClusterIP
      ports:
      - name: "http-port"
  answer.yaml: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      type: ClusterIP
      ports:
      - name: "http-port"
        protocol: "TCP"
        port: 8181
        targetPort: 80
      selector:
        app: nginx-app
  comment: |-
    this is comment here after correct answer
  author: |-
    Masaya Aoyama (@amsy810)
