---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q6
  labels:
    question.kontest.amsy.dev: "6"
data:
  question: |-
    Kubernetesでアプリケーションのスケーリングを行うためには、水平オートスケーラー(HPA)を使うことができます。
    HPAは、metrics-server等から取得できるPodのCPUやメモリの利用率などの値に基づいて、アプリケーションのレプリカ数を動的に増やしたり減らしたりする役割を持つリソースです。

    解答欄にあるDeploymentリソースを作成後、以下のようなHPAリソースを作成したとします。ところが、一定期間後にDeploymentリソースを再度適用すると、ある問題が生じることがわかりました。原因を突き止め、正しくオートスケールするように修正してください。

    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nginx-autoscale
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nginx-autoscale
      minReplicas: 2
      maxReplicas: 10
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
  hint: |-
    https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  base_content.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-autoscale
    spec:
      selector:
        matchLabels:
          run: nginx-autoscale
      replicas: 1
      template:
        metadata:
          labels:
            run: nginx-autoscale
        spec:
          containers:
          - name: nginx-autoscale
            image: nginx:1.19
            ports:
            - containerPort: 80
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 500m
  answer.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-autoscale
    spec:
      selector:
        matchLabels:
          run: nginx-autoscale
      template:
        metadata:
          labels:
            run: nginx-autoscale
        spec:
          containers:
          - name: nginx-autoscale
            image: nginx:1.19
            ports:
            - containerPort: 80
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 500m
  comment: |-
    【解説 by カサレアル】
    HPAは、定期的にDeploymentの spec.replicas の値を負荷状況に応じて書き換える、という動作をします（デフォルトでは15秒ごと）。
    元のDeploymentには spec.replicas: 1 の記述がありました。それを削除したのが解答例です。
    spec.replicas の値が設定されていると、次のような問題が発生します。
    1. 最初にDeploymentがデプロイすると、Podは spec.replicas で指定された1台になる
    2. 負荷が高くなってHPAが動くと、spec.minReplicas （今回は2）と spec.maxReplicas （今回は10）の間でPodの台数が増える
    3. Deploymentを再デプロイすると、Podの台数が再び減ってしまう。この際、Deploymentの spec.replicas まで減るか、 HPAの spec.minReplicas まで減るかは、HPAの動作のタイミングによる。
    このように、予測しづらい挙動となってしまいますので、HPA利用時はDeploymentに spec.replicas は指定しないほうが良いでしょう。
  author: |-
    Kohei Ota (@inductor)
