---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q7
  labels:
    question.kontest.amsy.dev: "7"
data:
  question: |-
    設定情報をKey-Valueとして保存できるリソースがConfigMapです。
    cndt-configというConfigMapをconfig-volumeという名前のボリュームとしてすべてののKey-Valueを一括で/config/mapディレクトリにマウントするように、以下Podのマニフェストファイルを変更してください。

    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
  hint: |-
    https://kubernetes.io/docs/concepts/configuration/configmap/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
        volumeMounts:
        - name: config-volume
          mountPath: /config/map
      volumes:
        - name: config-volume
          configMap:
            name: cndt-config
  comment: |-
    this is comment here after correct answer
  author: |-
    Yutaka Ichikawa (@cyberblack28)
