---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q7
  labels:
    question.kontest.amsy.dev: "7"
data:
  question: |-
    設定情報をKey-Valueとして保存できるリソースがConfigMapです。
    cndt-configというConfigMapをconfig-volumeという名前のボリュームとしてすべてのKey-Valueを一括で/config/mapディレクトリにマウントするように、以下Podのマニフェストファイルを変更してください。

    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
  hint: |-
    https://kubernetes.io/docs/concepts/configuration/configmap/
  base_content.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
  answer.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: nginx-configmap
      name: nginx-configmap
    spec:
      containers:
      - image: nginx
        name: nginx-configmap
        volumeMounts:
        - name: config-volume
          mountPath: /config/map
      volumes:
        - name: config-volume
          configMap:
            name: cndt-config
  comment: |-
    【解説 by カサレアル】 
    ConfigMapに保存された設定値を利用する方法は、主に下記の2つです。
    1. コンテナの環境変数として利用する
    2. ConfigMapをコンテナにボリュームとしてマウントする
    今回は2.の方法で利用します。この場合、まず spec.volumes[] にConfigMapをボリュームとして定義します。そして、そのボリュームを spec.containers[].volumeMounts[] に指定すればOKです。
  author: |-
    Yutaka Ichikawa (@cyberblack28)
