---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q9
  labels:
    question.kontest.amsy.dev: "9"
data:
  question: |-
    永続化領域として確保されるVolumeが、PersistentVolumeです。
    NFSを使用してcndt-pvという名前のPersistentVolumeを作成し、NFSサーバのIPを192.168.9.8、容量を8Gi、アクセスモードをRXW、Reclaim PolicyをRetain、そのボリュームが当該クラスタのノードの/var/lib/cndtにあることを明示するように以下マニフェストファイルに変更してください。

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: cndt-pv
      labels:
        type: local
    spec:
      storageClassName: cndt
  hint: |-
    https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  base_content.yaml: |-
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: cndt-pv
      labels:
        type: local
    spec:
      storageClassName: cndt
  answer.yaml: |-
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: cndt-pv
      labels:
        type: local
    spec:
      storageClassName: cndt
      capacity:
        storage: 8Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        server: 192.168.9.8
        path: /var/lib/cndt
  comment: |-
    this is comment here after correct answer
  author: |-
    Yutaka Ichikawa (@cyberblack28)
